const fs=require('fs'), vm=require('vm'); const R=process.argv[2];
const XLSX=require(process.argv[4]);
const ctx={console, window:{}, document:{getElementById:()=>({addEventListener(){} }), querySelectorAll:()=>[]}, setTimeout, Date, URL, XLSX};
ctx.window=ctx; vm.createContext(ctx);
for (const f of ['options.js','validation.js']) vm.runInContext(fs.readFileSync(R+'/'+f,'utf8'),ctx);
ctx.Persons={ctx:()=>({}),toast(){}};
vm.runInContext(fs.readFileSync(R+'/import.js','utf8'),ctx);
const T=ctx.Importer._test;
const wb=XLSX.read(fs.readFileSync(process.argv[3]),{type:'buffer'});
const all=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,raw:true,defval:null});
const hdr=all[0], body=all.slice(1);
const tpl=T.TEMPLATES.find(t=>t.detect(hdr)); console.log('template:', tpl&&tpl.id);
const regions=new Map(['Вінницька','Волинська','Дніпропетровська','Донецька','Житомирська','Закарпатська','Запорізька','Івано-Франківська','Київська','Кіровоградська','Луганська','Львівська','Миколаївська','Одеська','Полтавська','Рівненська','Сумська','Тернопільська','Харківська','Херсонська','Хмельницька','Черкаська','Чернівецька','Чернігівська','м. Київ','АР Крим','За кордоном'].map((n,i)=>[i+1,n]));
const list=tpl.parse(body,hdr,{regions, units:new Map(), cells:new Map(), programs:new Map([[1,'Супровід родин загиблих (200)']]), programByName:()=>1});
const main=list.filter(r=>!r.isRelative);
console.log('records',list.length,'main(fallen)',main.length,'relatives',list.length-main.length,'errors',list.filter(r=>r.errors.length).length);
console.log('fallen with birth',main.filter(r=>r.person.birth_date).length,'with burial date',main.filter(r=>r.person.burial_date).length,'with death',main.filter(r=>r.person.death_date).length);
console.log('relatives with phone', list.filter(r=>r.isRelative&&r.person.phone).length);
const w={}; list.forEach(r=>[...r.errors.map(e=>'E: '+e),...r.warnings].forEach(x=>{const k=x.replace(/«[^»]*»/g,'«…»').replace(/\d/g,'9').slice(0,80); w[k]=(w[k]||0)+1;}));
Object.entries(w).sort((a,b)=>b[1]-a[1]).forEach(([k,n])=>console.log('  ',n,'×',k));
